export const data = [
    "Get Started" , 
    "Account and pofile" , 
    "Authentication",
    "Repositories",
    "Enterprise administrators" ,
    "Billing and payments" ,
    "Site policy" ,
    "organization" ,
    "Code security" ,
    "Pull requests" ,
    "GitHub Issues" ,
    "GitHub Actions" ,
    "GitHub Copilot" ,
    "GitHub CodeSpaces " ,
    "Migrations" ,
    "GitHub packages" ,
    "Search on GitHub" ,
    "Apps" ,
    "Webhooks and events" ,
    "REST API" ,
    "GrahQL API",
    "GitHub CLI" ,
    "GitHub Discussions" ,
    "GitHub Sponsors" ,
    "Building communities" ,
    "GitHub Pages" ,
    "Education" ,
    "GitHub Desktop" ,
    "GitHub Support" ,
    "Electron" ,
    "CodeQL" ,
    "npm"
]